"""Add password_hash and approval_eligibility to customer_users

Revision ID: c11a3ec0ca6c
Revises: 401054ea18ca
Create Date: 2025-06-25 04:50:34.165969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11a3ec0ca6c'
down_revision = '401054ea18ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_eligibility', sa.JSON(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('approval_eligibility')

    # ### end Alembic commands ###
